// ALERT
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'


// ITEMS
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR'

export const GET_ITEM_BY_ID_SUCCESS = "GET_ITEM_BY_ID_SUCCESS"
export const GET_ITEM_BY_ID_ERROR = 'GET_ITEM_BY_ID_ERROR'

export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS"
export const CREATE_ITEM_ERROR = "CREATE_ITEM_ERROR"

export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_ERROR = "DELETE_ITEM_ERROR"

export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_ERROR = "UPDATE_ITEM_ERROR"